In [2]:
import pandas as pd
from sklearn.datasets import load_iris
iris = load_iris()

In [3]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [10]:
df['flower'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                5.1               3.5                1.4               0.2  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0       0  
1       0  
2       0  
3       0  
4       0

In [11]:
df['flower'] = df['flower'].apply(lambda x: iris.target_names[x])
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)   
0                5.1               3.5                1.4               0.2  \
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   flower  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [12]:
x = df.drop('flower', axis = 'columns')
y = df.flower

In [40]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [41]:
from sklearn.svm import SVC
model = SVC(kernel='rbf', gamma = 'auto')

In [42]:
model.fit(x_train, y_train)

SVC(gamma='auto')

In [43]:
model.score(x_test, y_test)

0.9666666666666667

In [39]:
model.C

1.0

In [44]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(kernel = 'linear', C = 10, gamma = 'auto'), x_train, y_train)

array([1.        , 0.91666667, 0.95833333, 0.875     , 1.        ])

In [45]:
cross_val_score(SVC(kernel = 'rbf', C = 10, gamma = 'auto'), x_train, y_train)

array([1.        , 0.91666667, 0.95833333, 0.875     , 1.        ])

In [47]:
cross_val_score(SVC(kernel = 'rbf', C = 20, gamma = 'auto'), x_train, y_train)

array([1.        , 0.91666667, 0.95833333, 0.875     , 1.        ])

In [51]:
import numpy as np
kernels = ['rbf', 'linear']
C = [1, 10, 20]
avg_scores = {}

for kval in kernels:
    for cval in C:
        cv_scores = cross_val_score(SVC(kernel = kval, C = cval, gamma = 'auto'), x_train, y_train)
        avg_scores[kval + '_' + str(cval)] = np.average(cv_scores)

avg_scores

{'rbf_1': 0.975,
 'rbf_10': 0.95,
 'rbf_20': 0.95,
 'linear_1': 0.975,
 'linear_10': 0.95,
 'linear_20': 0.95}

In [52]:
from sklearn.model_selection import GridSearchCV

clf = GridSearchCV(SVC(gamma = 'auto'), {
    'C': [1, 10, 20],
    'kernel': ['rbf', 'linear']
}, return_train_score=False)

clf

GridSearchCV(estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20], 'kernel': ['rbf', 'linear']})

In [53]:
clf.fit(x_train, y_train)
clf.cv_results_

{'mean_fit_time': array([0.        , 0.00319977, 0.00320954, 0.00159998, 0.00320034,
        0.00319972]),
 'std_fit_time': array([0.        , 0.0039189 , 0.0039309 , 0.00319996, 0.0039196 ,
        0.00391884]),
 'mean_score_time': array([0.00799809, 0.00159998, 0.        , 0.00159984, 0.00159965,
        0.        ]),
 'std_score_time': array([3.13264231e-06, 3.19995880e-03, 0.00000000e+00, 3.19967270e-03,
        3.19929123e-03, 0.00000000e+00]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20

In [54]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C   
0        0.00000      0.000000         0.007998        0.000003       1  \
1        0.00320      0.003919         0.001600        0.003200       1   
2        0.00321      0.003931         0.000000        0.000000      10   
3        0.00160      0.003200         0.001600        0.003200      10   
4        0.00320      0.003920         0.001600        0.003199      20   
5        0.00320      0.003919         0.000000        0.000000      20   

  param_kernel                         params  split0_test_score   
0          rbf      {'C': 1, 'kernel': 'rbf'}                1.0  \
1       linear   {'C': 1, 'kernel': 'linear'}                1.0   
2          rbf     {'C': 10, 'kernel': 'rbf'}                1.0   
3       linear  {'C': 10, 'kernel': 'linear'}                1.0   
4          rbf     {'C': 20, 'kernel': 'rbf'}                1.0   
5       linear  {'C': 20, 'kernel': 'linear'}                1.0   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score   
0           0.916667           1.000000           0.958333                1.0  \
1           0.958333           0.958333           0.958333                1.0   
2           0.916667           0.958333           0.875000                1.0   
3           0.916667           0.958333           0.875000                1.0   
4           0.916667           0.958333           0.875000                1.0   
5           0.916667           0.958333           0.875000                1.0   

   mean_test_score  std_test_score  rank_test_score  
0            0.975        0.033333                1  
1            0.975        0.020412                1  
2            0.950        0.048591                3  
3            0.950        0.048591                3  
4            0.950        0.048591                3  
5            0.950        0.048591                3

In [55]:
df[['param_C', 'param_kernel', 'mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf            0.975
1       1       linear            0.975
2      10          rbf            0.950
3      10       linear            0.950
4      20          rbf            0.950
5      20       linear            0.950

In [56]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_impl',
 '_check_feature_names',
 '_check_n_features',
 '_check_refit_for_multimetric',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_required_parameters',
 '_run_search',
 '_select_best_index',
 '_validate_data',
 '_validate_params',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'feature_names_in_',
 'fit',
 'get_params',
 'inverse_transform',
 

In [57]:
clf.best_estimator_

SVC(C=1, gamma='auto')

In [58]:
clf.best_index_

0

In [59]:
clf.best_params_

{'C': 1, 'kernel': 'rbf'}

In [60]:
clf.best_score_

0.975

In [63]:
from sklearn.model_selection import RandomizedSearchCV
clf = RandomizedSearchCV(SVC(gamma = 'auto'), {
    'C': [1, 10, 20],
    'kernel': ['rbf', 'linear']
}, n_iter=2)
clf.fit(x_train, y_train)

RandomizedSearchCV(estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [64]:
df = pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel   
0         0.0016      0.003201         0.004801         0.00392       linear  \
1         0.0032      0.003919         0.000000         0.00000          rbf   

  param_C                         params  split0_test_score   
0      20  {'kernel': 'linear', 'C': 20}                1.0  \
1      20     {'kernel': 'rbf', 'C': 20}                1.0   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score   
0           0.916667           0.958333              0.875                1.0  \
1           0.916667           0.958333              0.875                1.0   

   mean_test_score  std_test_score  rank_test_score  
0             0.95        0.048591                1  
1             0.95        0.048591                1

In [66]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_params = {
    'svm': {
        'model': SVC(gamma = 'auto'),
        'params': {
            'kernel': ['rbf', 'linear'],
            'C': [1, 10, 20]
        }
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params': {
            'n_estimators': [1, 5, 10]
        }
    },
    'logistic_regression': {
        'model': LogisticRegression(solver = 'liblinear', multi_class='auto'),
        'params': {
            'C': [1, 5, 10]
        }
    }
}

In [99]:
scores = []

for model, mp in model_params.items():
    clf = GridSearchCV(mp['model'], mp['params'], return_train_score=False)
    clf.fit(x_train, y_train)
    scores.append({
        'model': model,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
scores

[{'model': 'svm',
  'best_score': 0.975,
  'best_params': {'C': 1, 'kernel': 'rbf'}},
 {'model': 'random_forest',
  'best_score': 0.9416666666666667,
  'best_params': {'n_estimators': 5}},
 {'model': 'logistic_regression',
  'best_score': 0.9583333333333334,
  'best_params': {'C': 1}}]

In [100]:
df = pd.DataFrame(scores)

In [101]:
df

model  best_score                best_params
0                  svm    0.975000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.941667        {'n_estimators': 5}
2  logistic_regression    0.958333                   {'C': 1}