In [1]:
from sklearn.datasets import load_iris
iris = load_iris()

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier

In [3]:
from sklearn.model_selection import cross_val_score

In [5]:
y = [iris.target_names[i] for i in iris.target]
y

['setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'setosa',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',
 'versicolor',


In [14]:
lr_scores = cross_val_score(LogisticRegression(solver='liblinear', multi_class='ovr'), iris.data, y)
lr_scores

array([1.        , 0.96666667, 0.93333333, 0.9       , 1.        ])

In [15]:
svm_scores = cross_val_score(SVC(), iris.data, y)
svm_scores

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [22]:
dt_scores = cross_val_score(tree.DecisionTreeClassifier(), iris.data, y)
dt_scores

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [17]:
rf_scores = cross_val_score(RandomForestClassifier(), iris.data, y)
rf_scores

array([0.96666667, 0.96666667, 0.9       , 0.93333333, 1.        ])

In [19]:
import numpy as np
logistic_avg = np.average(lr_scores)
svm_avg = np.average(svm_scores)
dt_avg = np.average(dt_scores)
rf_avg = np.average(rf_scores)

In [20]:
logistic_avg, svm_avg, dt_avg, rf_avg

(0.9600000000000002,
 0.9666666666666666,
 0.9666666666666668,
 0.9533333333333334)