In [1]:
import numpy as np

In [2]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [3]:
profit = revenue - expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [4]:
price_per_unit = np.array([1000,400,1200])
units = np.array([[30,40,50],[5,10,15],[2,5,7]])

In [5]:
np.dot(price_per_unit, units)

array([34400, 50000, 64400])

# Exercise

In [6]:
revenue_in_dollar = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])

In [7]:
revenue_in_ruppes = 75 * revenue_in_dollar
revenue_in_ruppes

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [14]:
per_month_sale = np.array([[50, 10, 40], [60, 13, 17], [25, 5, 52]])
price_per_unit = np.array([[20], [30], [15]])

In [15]:
total_sale = np.dot(per_month_sale, price_per_unit)
total_sale

array([[1900],
       [1845],
       [1430]])

# Method 2

In [16]:
per_month_sale = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])
price_per_unit = np.array([20, 30, 15])

In [17]:
total_sale = np.dot(price_per_unit, per_month_sale)
total_sale

array([1900, 2640, 1430])