# Welcome to NumPy Tutorial

In [1]:
import numpy as np

In [2]:
print('Hello World')

Hello World


In [3]:
np.__version__

'1.24.3'

In [4]:
arr = np.array([1, 2, 3, 4, 5])

In [5]:
print(arr)

[1 2 3 4 5]


In [6]:
np.ndim(arr)

1

In [7]:
arr2 = [[1, 2, 3], [4, 5, 6]]
np.ndim(arr2)

2

In [8]:
arr3 = np.array([1, 2, 3, 4, 5,6], ndmin = 5)

In [9]:
print(arr3)

[[[[[1 2 3 4 5 6]]]]]


In [10]:
print(np.ndim(arr3))

5


In [11]:
print(arr2)

[[1, 2, 3], [4, 5, 6]]


In [12]:
print(arr)

[1 2 3 4 5]


In [13]:
print(arr[1:4])

[2 3 4]


In [14]:
print(arr[-4:-1])

[2 3 4]


In [15]:
arr4 = np.array([1, 2, 3, 4, 5, 6], dtype='S')

In [16]:
print(arr4)

[b'1' b'2' b'3' b'4' b'5' b'6']


In [17]:
print(np.array(arr4, dtype='f'))

[1. 2. 3. 4. 5. 6.]


In [18]:
newArray = arr4.astype('f')

In [19]:
print(newArray)

[1. 2. 3. 4. 5. 6.]


In [20]:
arr5 = arr4.copy()

In [21]:
arr6 = arr4.view()

In [22]:
print(arr5, arr6)

[b'1' b'2' b'3' b'4' b'5' b'6'] [b'1' b'2' b'3' b'4' b'5' b'6']


In [23]:
print(arr5.base)

None


In [24]:
print(arr6.base)

[b'1' b'2' b'3' b'4' b'5' b'6']


In [25]:
arr6[3] = 's'

In [26]:
arr6

array([b'1', b'2', b'3', b's', b'5', b'6'], dtype='|S1')

In [27]:
arr4

array([b'1', b'2', b'3', b's', b'5', b'6'], dtype='|S1')

In [28]:
arr = np.array([1, 2, 3, 4, 5, 6])

In [29]:
arr.reshape((3, 2))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
print(arr)

[1 2 3 4 5 6]


In [31]:
arr.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr = arr.reshape((2, -1))

In [33]:
np.nditer(arr)


In [36]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.nditer(arr)

In [39]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [40]:
np.ravel


<function numpy.ravel(a, order='C')>

In [41]:
np.ravel(arr)

array([1, 2, 3, 4, 5, 6])

In [42]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
for x in np.ravel(arr):
    print(x)

1
2
3
4
5
6


In [44]:
for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6


In [46]:
for x in arr.reshape(-1):
    print(x)

1
2
3
4
5
6


In [49]:
for x, i in np.ndenumerate(arr):
    print(x, i)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [50]:
arr1 = np.array([[1, 2], [3, 4], [5, 6]])
arr2 = np.array([[7, 8], [9, 10], [11, 12]])

In [53]:
print(np.concatenate((arr1, arr2), axis = 0))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [54]:
print(np.concatenate((arr1, arr2), axis = 1))

[[ 1  2  7  8]
 [ 3  4  9 10]
 [ 5  6 11 12]]


In [55]:
print(np.stack((arr1, arr2), axis=0))

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
print(np.stack(()))