In [1]:
import tensorflow as tf
import numpy as np
import os

In [70]:
from simple_image_download import simple_image_download as simp
import os

In [3]:
response = simp.simple_image_download
keywords = ['cat', 'dog']

In [4]:
for item in keywords:
    response().download(item, 100)

[========================================================================] 100%
[========================================================================] 100%


In [16]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

In [17]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [18]:
list(tf_dataset)

[<tf.Tensor: shape=(), dtype=int32, numpy=21>,
 <tf.Tensor: shape=(), dtype=int32, numpy=22>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-108>,
 <tf.Tensor: shape=(), dtype=int32, numpy=31>,
 <tf.Tensor: shape=(), dtype=int32, numpy=-1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=32>,
 <tf.Tensor: shape=(), dtype=int32, numpy=34>,
 <tf.Tensor: shape=(), dtype=int32, numpy=31>]

In [19]:
for item in tf_dataset.as_numpy_iterator():
    print(item)

21
22
-108
31
-1
32
34
31


In [20]:
tf_dataset = tf_dataset.filter(lambda x: x > 0)
tf_dataset

<_FilterDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [21]:
list(tf_dataset)

[<tf.Tensor: shape=(), dtype=int32, numpy=21>,
 <tf.Tensor: shape=(), dtype=int32, numpy=22>,
 <tf.Tensor: shape=(), dtype=int32, numpy=31>,
 <tf.Tensor: shape=(), dtype=int32, numpy=32>,
 <tf.Tensor: shape=(), dtype=int32, numpy=34>,
 <tf.Tensor: shape=(), dtype=int32, numpy=31>]

In [22]:
for i in tf_dataset:
    print(i.numpy())

21
22
31
32
34
31


In [23]:
tf_dataset = tf_dataset.shuffle(3)
list(tf_dataset)

[<tf.Tensor: shape=(), dtype=int32, numpy=22>,
 <tf.Tensor: shape=(), dtype=int32, numpy=31>,
 <tf.Tensor: shape=(), dtype=int32, numpy=34>,
 <tf.Tensor: shape=(), dtype=int32, numpy=32>,
 <tf.Tensor: shape=(), dtype=int32, numpy=31>,
 <tf.Tensor: shape=(), dtype=int32, numpy=21>]

In [24]:
tf_dataset = tf_dataset.map(lambda x: x * 72)
list(tf_dataset)

[<tf.Tensor: shape=(), dtype=int32, numpy=1584>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2304>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1512>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2232>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2232>,
 <tf.Tensor: shape=(), dtype=int32, numpy=2448>]

In [25]:
list(tf_dataset.take(2))

[<tf.Tensor: shape=(), dtype=int32, numpy=2232>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1512>]

In [26]:
list(tf_dataset.batch(2))

[<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2232, 2304])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2448, 1584])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2232, 1512])>]

In [27]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

## Perform in One Shot

In [28]:
dataset_in_one_shot = tf.data.Dataset.from_tensor_slices(daily_sales_numbers).filter(lambda x: x > 0).map(lambda y: y * 72).shuffle(3).batch(2)

In [29]:
list(dataset_in_one_shot)

[<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1512, 1584])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2304, 2232])>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([2232, 2448])>]

## Image Dataset

In [38]:
list(tf.data.Dataset.list_files('*/*'))

[<tf.Tensor: shape=(), dtype=string, numpy=b'.\\images\\dog'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'.\\.ipynb_checkpoints\\PipeLine-checkpoint.ipynb'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'.\\images\\cat'>]

In [39]:
img_dataset = tf.data.Dataset.list_files('images/*/*')
len(img_dataset)

190

In [76]:
img_dataset = img_dataset.shuffle(200)

In [77]:
list(img_dataset.take(10))

[<tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_63.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_83.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\dog\\dog_29.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_77.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_7.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_18.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_72.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_84.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\dog\\dog_3.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\dog\\dog_38.jpeg'>]

In [87]:
def get_labels(path):
    return tf.strings.split(path, os.path.sep)[-2]

In [88]:
for item in img_dataset.take(10).as_numpy_iterator():
    print(get_labels(item))

tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)
tf.Tensor(b'cat', shape=(), dtype=string)


In [71]:
os.path.sep

'\\'

In [96]:
def process_image(path):
    label = get_labels(path)
    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, (128, 128))
    return img, label

In [99]:
for item in img_dataset.take(2):
    img, label = process_image(item)
    print(img[0][0].numpy())
    print(label.numpy())

[175.3789    75.83594   12.902344]
b'dog'
[2.3125 8.3125 6.3125]
b'cat'


In [100]:
list(img_dataset)

[<tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_46.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_81.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\dog\\dog_9.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\dog\\dog_61.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_72.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\dog\\dog_6.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\dog\\dog_15.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_5.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_59.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\dog\\dog_21.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_50.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_27.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\cat\\cat_4.jpeg'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'images\\do

In [102]:
temp = img_dataset.map(process_image)

In [107]:
list(temp.take(1))

[(<tf.Tensor: shape=(128, 128, 3), dtype=float32, numpy=
  array([[[235.21277, 237.21277, 234.21277],
          [234.     , 235.     , 230.     ],
          [236.     , 236.     , 234.     ],
          ...,
          [233.     , 237.     , 236.     ],
          [233.     , 237.     , 236.     ],
          [232.     , 238.     , 236.     ]],
  
         [[234.21875, 236.21875, 233.21875],
          [235.     , 235.     , 233.     ],
          [234.     , 234.     , 232.     ],
          ...,
          [232.     , 236.     , 235.     ],
          [232.     , 238.     , 236.     ],
          [232.     , 238.     , 236.     ]],
  
         [[234.     , 236.     , 233.     ],
          [234.     , 234.     , 232.     ],
          [235.     , 235.     , 233.     ],
          ...,
          [232.     , 236.     , 235.     ],
          [231.     , 237.     , 235.     ],
          [231.     , 237.     , 235.     ]],
  
         ...,
  
         [[125.     , 115.     , 105.     ],
          [124

In [108]:
n = len(img_dataset)
n

190

In [110]:
int(n * 0.8)

152

In [111]:
n - 152

38

In [112]:
train_size = int(n * 0.8)
train_size

152

In [113]:
train_dataset = img_dataset.take(train_size)
test_dataset =  img_dataset.skip(train_size)

In [114]:
len(train_dataset)

152

In [115]:
len(test_dataset)

38