In [1]:
import tensorflow as tf
import os

In [2]:
txt_dataset = tf.data.Dataset.list_files('reviews/*/*')
list(txt_dataset)

[<tf.Tensor: shape=(), dtype=string, numpy=b'reviews\\negative\\neg_1.txt'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'reviews\\negative\\neg_2.txt'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'reviews\\negative\\neg_3.txt'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'reviews\\positive\\pos_3.txt'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'reviews\\positive\\pos_1.txt'>,
 <tf.Tensor: shape=(), dtype=string, numpy=b'reviews\\positive\\pos_2.txt'>]

In [16]:
def get_length(path):
    text = tf.io.read_file(path)
    return len(text.numpy())

In [19]:
for item in txt_dataset:
    print(get_length(item))

934
0
998
0
1761
748


In [26]:
def process_text(path):
    text = tf.io.read_file(path)
    label = tf.strings.split(path, os.path.sep)[-2]
    return text, label

In [34]:
for item in txt_dataset:
    text, label = process_text(item)
    print('-------------->', text.numpy())
    print()
    print(label.numpy())
    print()
    print()

--------------> b''

b'negative'


--------------> b"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I wo

In [35]:
txt_dataset = txt_dataset.map(process_text)
list(txt_dataset)

[(<tf.Tensor: shape=(), dtype=string, numpy=b"This show was an amazing, fresh & innovative idea in the 70's when it first aired. The first 7 or 8 years were brilliant, but things dropped off after that. By 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.<br /><br />It's truly disgraceful how far this show has fallen. The writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. I find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. How can one recognize such brilliance and then see fit to replace it with such mediocrity? I felt I must give 2 stars out of respect for the original cast that made this show such a huge success. As it is now, the show is just awful. I can't believe it's still on the air.">,
  <tf.Tensor: sh

In [36]:
for text, label in txt_dataset.as_numpy_iterator():
    print(text)
    print(label)
    print()
    print()

b''
b'positive'


b"One of the other reviewers has mentioned that after watching just 1 Oz episode you'll be hooked. They are right, as this is exactly what happened with me.<br /><br />The first thing that struck me about Oz was its brutality and unflinching scenes of violence, which set in right from the word GO. Trust me, this is not a show for the faint hearted or timid. This show pulls no punches with regards to drugs, sex or violence. Its is hardcore, in the classic use of the word.<br /><br />It is called OZ as that is the nickname given to the Oswald Maximum Security State Penitentary. It focuses mainly on Emerald City, an experimental section of the prison where all the cells have glass fronts and face inwards, so privacy is not high on the agenda. Em City is home to many..Aryans, Muslims, gangstas, Latinos, Christians, Italians, Irish and more....so scuffles, death stares, dodgy dealings and shady agreements are never far away.<br /><br />I would say the main appeal of the sh

In [37]:
len(txt_dataset)

6

In [39]:
txt_dataset = txt_dataset.filter(lambda text, label: text != '')

In [41]:
list(txt_dataset)

[(<tf.Tensor: shape=(), dtype=string, numpy=b"This show was an amazing, fresh & innovative idea in the 70's when it first aired. The first 7 or 8 years were brilliant, but things dropped off after that. By 1990, the show was not really funny anymore, and it's continued its decline further to the complete waste of time it is today.<br /><br />It's truly disgraceful how far this show has fallen. The writing is painfully bad, the performances are almost as bad - if not for the mildly entertaining respite of the guest-hosts, this show probably wouldn't still be on the air. I find it so hard to believe that the same creator that hand-selected the original cast also chose the band of hacks that followed. How can one recognize such brilliance and then see fit to replace it with such mediocrity? I felt I must give 2 stars out of respect for the original cast that made this show such a huge success. As it is now, the show is just awful. I can't believe it's still on the air.">,
  <tf.Tensor: sh

In [42]:
for text, label in txt_dataset.as_numpy_iterator():
    print(text)
    print(label)
    print()
    print()

b"Basically there's a family where a little boy (Jake) thinks there's a zombie in his closet & his parents are fighting all the time.<br /><br />This movie is slower than a soap opera... and suddenly, Jake decides to become Rambo and kill the zombie.<br /><br />OK, first of all when you're going to make a film you must Decide if its a thriller or a drama! As a drama the movie is watchable. Parents are divorcing & arguing like in real life. And then we have Jake with his closet which totally ruins all the film! I expected to see a BOOGEYMAN similar movie, and instead i watched a drama with some meaningless thriller spots.<br /><br />3 out of 10 just for the well playing parents & descent dialogs. As for the shots with Jake: just ignore them."
b'negative'


b"This show was an amazing, fresh & innovative idea in the 70's when it first aired. The first 7 or 8 years were brilliant, but things dropped off after that. By 1990, the show was not really funny anymore, and it's continued its decl